@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class AdminController {
  - transactionService: TransactionService
  - userService: UserService
  + deleteUser(Long): ResponseEntity<String>
  + getAllUsers(): ResponseEntity<Iterable<User>>
  + getUserById(Long): ResponseEntity<User>
  + getUserTransactions(Long): ResponseEntity<List<Transaction>>
}
class ApplicationConfig {
  - repository: UserRepository
  + userDetailsService(): UserDetailsService
  + authenticationManager(AuthenticationConfiguration): AuthenticationManager
  + authenticationProvider(): AuthenticationProvider
  + passwordEncoder(): PasswordEncoder
}
class AuthController {
  - authenticationService: AuthenticationService
  + register(RegisterRequest, HttpServletResponse): ResponseEntity<Map<String, String>>
  - addJwtCookie(HttpServletResponse, String): void
  + authenticate(AuthenticationRequest, HttpServletResponse): ResponseEntity<Map<String, String>>
}
entity AuthenticationRequest << record >> {
  - password: String
  - email: String
  + email(): String
  + password(): String
}
entity AuthenticationResponse << record >> {
  - token: String
  + token(): String
}
class AuthenticationService {
  - authenticationManager: AuthenticationManager
  - tokenRepository: TokenRepository
  - passwordEncoder: PasswordEncoder
  - userService: UserService
  - userRepository: UserRepository
  - jwtService: JwtService
  + register(RegisterRequest): String
  - saveUserToken(User, String): void
  + authenticate(AuthenticationRequest): String
  - revokeAllUserTokens(User): void
}
class Budget {
  - threshold: Double
  - endDate: LocalDate
  - user: User
  - status: BudgetStatus
  - spentAmount: Double
  - category: Category
  - spendingLimit: Double
  - startDate: LocalDate
  - id: Long
  + getSpendingLimit(): Double
  + setId(Long): void
  + builder(): BudgetBuilder
  + getId(): Long
  + getUser(): User
  + setThreshold(Double): void
  + setStatus(BudgetStatus): void
  + getCategory(): Category
  + getSpentAmount(): Double
  + getStatus(): BudgetStatus
  + setSpendingLimit(Double): void
  - $default$spentAmount(): Double
  + setEndDate(LocalDate): void
  + getThreshold(): Double
  + setUser(User): void
  + getStartDate(): LocalDate
  + setSpentAmount(Double): void
  + setCategory(Category): void
  + getEndDate(): LocalDate
  + setStartDate(LocalDate): void
}
class BudgetBuilder {
  - spendingLimit: Double
  - endDate: LocalDate
  - category: Category
  - spentAmount$value: Double
  - threshold: Double
  - spentAmount$set: boolean
  - user: User
  - id: Long
  - startDate: LocalDate
  - status: BudgetStatus
  + user(User): BudgetBuilder
  + id(Long): BudgetBuilder
  + category(Category): BudgetBuilder
  + spendingLimit(Double): BudgetBuilder
  + spentAmount(Double): BudgetBuilder
  + toString(): String
  + threshold(Double): BudgetBuilder
  + startDate(LocalDate): BudgetBuilder
  + endDate(LocalDate): BudgetBuilder
  + status(BudgetStatus): BudgetBuilder
  + build(): Budget
}
class BudgetController {
  - budgetService: BudgetService
  - userService: UserService
  + getActiveBudgets(UserDetails): ResponseEntity<List<BudgetResponse>>
  - toResponse(Budget): BudgetResponse
  + getNearLimitBudgets(UserDetails): ResponseEntity<List<BudgetResponse>>
  + getAllBudgets(UserDetails): ResponseEntity<List<BudgetResponse>>
  + getExpiredBudgets(UserDetails): ResponseEntity<List<BudgetResponse>>
  + deleteBudget(UserDetails, Long): ResponseEntity<Void>
  + editBudget(UserDetails, Long, CreateBudgetRequest): ResponseEntity<BudgetResponse>
  + deleteExpiredBudgets(UserDetails): ResponseEntity<Void>
  + addBudget(UserDetails, CreateBudgetRequest): ResponseEntity<BudgetResponse>
  + deleteAllBudgets(UserDetails): ResponseEntity<Void>
  + getExeededLimitBudgets(UserDetails): ResponseEntity<List<BudgetResponse>>
  - toResponseList(List<Budget>): List<BudgetResponse>
}
class BudgetExceededLimitEvent {
  - categoryName: String
  - exceededAmount: BigDecimal
  + getCategoryName(): String
  + getExceededAmount(): BigDecimal
  + getType(): NotificationEventType
}
class BudgetNearLimitEvent {
  - categoryName: String
  - exceededAmount: BigDecimal
  + getExceededAmount(): BigDecimal
  + getCategoryName(): String
  + getType(): NotificationEventType
}
interface BudgetRepository << interface >> {
  + findByUserIdAndEndDateGreaterThanEqual(Long, LocalDate, Pageable): List<Budget>
  + countByUserIdAndEndDateGreaterThanEqual(Long, LocalDate): Long
  + findByUserIdAndEndDateGreaterThanEqual(Long, LocalDate): List<Budget>
  + findByUserIdAndEndDateAfter(Long, LocalDate, Pageable): List<Budget>
  + findByUserId(Long): List<Budget>
  + findByIdAndUserId(Long, Long): Optional<Budget>
  + findByUserIdAndStatus(Long, BudgetStatus): List<Budget>
  + findByUserIdAndEndDateGreaterThanEqualOrderByStartDateDescIdDesc(Long, LocalDate, Pageable): List<Budget>
  + findByUserIdOrderByStartDateDescIdDesc(Long, Pageable): List<Budget>
  + findByUserIdAndCategoryId(Long, Long): Optional<Budget>
  + countByUserIdAndEndDateLessThan(Long, LocalDate): Long
  + findByUserIdAndEndDateLessThan(Long, LocalDate): List<Budget>
}
class BudgetResponse {
  - userId: Long
  - categoryId: Long
  - id: Long
  - threshold: Double
  - endDate: LocalDate
  - spentAmount: Double
  - spendingLimit: Double
  - startDate: LocalDate
  - status: BudgetStatus
  + getId(): Long
  + getUserId(): Long
  + getCategoryId(): Long
  + getSpendingLimit(): Double
  + getSpentAmount(): Double
  + getThreshold(): Double
  + getStartDate(): LocalDate
  + getEndDate(): LocalDate
  + getStatus(): BudgetStatus
}
class BudgetService {
  - budgetRepository: BudgetRepository
  - categoryRepository: CategoryRepository
  - userRepository: UserRepository
  - notificationService: NotificationService
  + getActiveBudgets(Long): List<Budget>
  + getAllBudgets(Long): List<Budget>
  + countActiveBudgets(Long): Long
  + onTransactionDeleted(Long, Long, Double, LocalDate): void
  + addBudget(Long, CreateBudgetRequest): Budget
  + deleteExpiredBudgets(Long): void
  + deleteBudgetById(Long, Long): void
  + getExpiredBudgets(Long): List<Budget>
  + getBudgetById(Long, Long): Budget
  - updateBudgetSpending(Budget, Double): void
  + editBudget(Long, Long, CreateBudgetRequest): Budget
  + getNearLimitBudgets(Long): List<Budget>
  + getActiveBudgets(Long, int): List<Budget>
  + countExpiredBudgets(Long): Long
  + getExeededLimitBudgets(Long): List<Budget>
  + deleteAllBudgets(Long): void
  + onTransactionAdded(Long, Long, Double, LocalDate): void
}
enum BudgetStatus << enumeration >> {
  + NEAR_LIMIT: 
  + ON_TRACK: 
  + EXCEEDED_LIMIT: 
  + values(): BudgetStatus[]
  + valueOf(String): BudgetStatus
}
class CSVExporter {
  + export(List<Transaction>, String): File
  - getCategoryOrSource(Transaction): String
}
class Category {
  - name: String
  - user: User
  - id: Long
  - type: CategoryType
  + getId(): Long
  + getUser(): User
  + getType(): CategoryType
  + getName(): String
  + setId(Long): void
  + setUser(User): void
  + setType(CategoryType): void
  + setName(String): void
  + builder(): CategoryBuilder
}
class CategoryBuilder {
  - name: String
  - user: User
  - type: CategoryType
  - id: Long
  + id(Long): CategoryBuilder
  + user(User): CategoryBuilder
  + type(CategoryType): CategoryBuilder
  + name(String): CategoryBuilder
  + build(): Category
  + toString(): String
}
class CategoryController {
  - categoryService: CategoryService
  - userService: UserService
  + getCustomCategories(UserDetails): ResponseEntity<List<CategoryResponse>>
  + addCustomCategory(UserDetails, CreateCategoryRequest): ResponseEntity<CategoryResponse>
  + addBuiltInCategory(CreateCategoryRequest): ResponseEntity<CategoryResponse>
  + deleteCustomCategory(UserDetails, Long): ResponseEntity<?>
  - toResponse(Category): CategoryResponse
  - toResponseList(List<Category>): List<CategoryResponse>
  + editCustomCategory(UserDetails, Long, CreateCategoryRequest): ResponseEntity<CategoryResponse>
  + getAllCategories(UserDetails): ResponseEntity<List<CategoryResponse>>
  + getBuiltInCategories(): ResponseEntity<List<CategoryResponse>>
}
interface CategoryRepository << interface >> {
  + findByUserIsNull(): List<Category>
  + findByType(CategoryType): List<Category>
  + findByUserId(Long): List<Category>
  + findByIdAndUserId(Long, Long): Optional<Category>
  + existsByTypeAndNameIgnoreCase(CategoryType, String): boolean
  + findByUserIdOrType(Long, CategoryType): List<Category>
  + findAccessibleCategory(Long, Long): Optional<Category>
  + existsByUserIdAndNameIgnoreCase(Long, String): boolean
}
class CategoryResponse {
  - userId: Long
  - id: Long
  - name: String
  - type: CategoryType
  + getId(): Long
  + getUserId(): Long
  + getType(): CategoryType
  + getName(): String
}
class CategoryService {
  - categoryRepository: CategoryRepository
  - userRepository: UserRepository
  + getAllCategories(Long): List<Category>
  + getCategoryById(Long, Long): Category
  - normalizeName(String): String
  + addCustomCategory(Long, CreateCategoryRequest): Category
  + getBuiltInCategories(): List<Category>
  + editCustomCategory(Long, Long, CreateCategoryRequest): Category
  + addBuiltInCategory(CreateCategoryRequest): Category
  + getCustomCategories(Long): List<Category>
  + deleteCustomCategory(Long, Long): void
  - ensureNotBuiltInName(String): void
  - ensureUniqueForUser(Long, String, Long): void
}
enum CategoryType << enumeration >> {
  + CUSTOM: 
  + BUILT_IN: 
  + valueOf(String): CategoryType
  + values(): CategoryType[]
}
class CreateBudgetRequest {
  - threshold: Double
  ~ categoryId: Long
  ~ spendingLimit: Double
  ~ endDate: LocalDate
  + getEndDate(): LocalDate
  + getCategoryId(): Long
  + getSpendingLimit(): Double
  + getThreshold(): Double
  + setCategoryId(Long): void
  + setSpendingLimit(Double): void
  + setThreshold(Double): void
  + setEndDate(LocalDate): void
  + equals(Object): boolean
  + toString(): String
  # canEqual(Object): boolean
  + hashCode(): int
}
class CreateCategoryRequest {
  - type: CategoryType
  - name: String
  + getType(): CategoryType
  + getName(): String
  + setType(CategoryType): void
  + setName(String): void
  + equals(Object): boolean
  # canEqual(Object): boolean
  + hashCode(): int
  + toString(): String
}
class CreateTransactionRequest {
  - categoryId: Long
  - date: LocalDate
  - description: String
  - source: String
  - amount: double
  - type: TransactionType
  + getSource(): String
  + getAmount(): double
  + getType(): TransactionType
  + getDate(): LocalDate
  + equals(Object): boolean
  + getCategoryId(): Long
  + getDescription(): String
  + toString(): String
  + setSource(String): void
  + setAmount(double): void
  + setType(TransactionType): void
  + setDate(LocalDate): void
  + setDescription(String): void
  # canEqual(Object): boolean
  + hashCode(): int
  + setCategoryId(Long): void
}
class DashboardController {
  - transactionService: TransactionService
  - budgetService: BudgetService
  - goalService: GoalService
  - userService: UserService
  + getDashboard(UserDetails): ResponseEntity<DashboardResponse>
}
class DashboardResponse {
  - recentTransactions: List<TransactionResponse>
  - monthlyExpense: BigDecimal
  - activeBudgetItems: List<BudgetResponse>
  - monthlyIncome: BigDecimal
  - activeGoals: Integer
  - activeBudgets: Integer
  - totalBalance: BigDecimal
  - numberOfTransactions: Integer
  + getActiveBudgetItems(): List<BudgetResponse>
  + getTotalBalance(): BigDecimal
  + setActiveGoals(Integer): void
  + toString(): String
  + equals(Object): boolean
  + setActiveBudgetItems(List<BudgetResponse>): void
  + getMonthlyIncome(): BigDecimal
  + setNumberOfTransactions(Integer): void
  + getMonthlyExpense(): BigDecimal
  + getRecentTransactions(): List<TransactionResponse>
  + getActiveBudgets(): Integer
  + getActiveGoals(): Integer
  + setRecentTransactions(List<TransactionResponse>): void
  + getNumberOfTransactions(): Integer
  + setTotalBalance(BigDecimal): void
  + setMonthlyExpense(BigDecimal): void
  + hashCode(): int
  # canEqual(Object): boolean
  + setMonthlyIncome(BigDecimal): void
  + setActiveBudgets(Integer): void
}
class ExcelExporter {
  - getCategoryOrSource(Transaction): String
  + export(List<Transaction>, String): File
}
class ExporterFactory {
  - pdfExporter: PDFExporter
  - excelExporter: ExcelExporter
  - csvExporter: CSVExporter
  + getExporter(ReportFormat): ReportExporter
}
class GlobalExceptionHandler {
  + handleNotFound(TransactionNotFoundException): Map<String, Object>
}
class Goal {
  - status: GoalStatus
  - user: User
  - iconClass: String
  - currentAmount: Double
  - id: Long
  - iconColor: String
  - goalName: String
  - targetAmount: double
  - deadline: LocalDate
  + getUser(): User
  + setId(Long): void
  + getId(): Long
  + getGoalName(): String
  + builder(): GoalBuilder
  + setIconColor(String): void
  + getTargetAmount(): double
  + setUser(User): void
  + setStatus(GoalStatus): void
  + setGoalName(String): void
  + setCurrentAmount(Double): void
  + getIconColor(): String
  + getDeadline(): LocalDate
  + getCurrentAmount(): Double
  - $default$currentAmount(): Double
  + setTargetAmount(double): void
  + setIconClass(String): void
  + getStatus(): GoalStatus
  + getIconClass(): String
  + setDeadline(LocalDate): void
}
class GoalBuilder {
  - targetAmount: double
  - id: Long
  - currentAmount$value: Double
  - iconClass: String
  - goalName: String
  - user: User
  - deadline: LocalDate
  - status: GoalStatus
  - currentAmount$set: boolean
  - iconColor: String
  + goalName(String): GoalBuilder
  + id(Long): GoalBuilder
  + user(User): GoalBuilder
  + targetAmount(double): GoalBuilder
  + deadline(LocalDate): GoalBuilder
  + currentAmount(Double): GoalBuilder
  + status(GoalStatus): GoalBuilder
  + iconClass(String): GoalBuilder
  + iconColor(String): GoalBuilder
  + build(): Goal
  + toString(): String
}
class GoalController {
  - goalService: GoalService
  - userService: UserService
  + updateProgress(long, double, UserDetails): ResponseEntity<GoalResponse>
  + deleteGoal(long, UserDetails): ResponseEntity<Void>
  + getUserGoals(UserDetails): ResponseEntity<List<GoalResponse>>
  + editGoal(Long, GoalRequest, UserDetails): ResponseEntity<GoalResponse>
  + addGoal(GoalRequest, UserDetails): ResponseEntity<GoalResponse>
}
class GoalReminderEvent {
  - goalName: String
  - deadline: LocalDate
  + getType(): NotificationEventType
  + getGoalName(): String
  + getDeadline(): LocalDate
}
class GoalReminderScheduler {
  - goalRepository: GoalRepository
  - notificationService: NotificationService
  + sendGoalReminders(): void
}
interface GoalRepository << interface >> {
  + findByUserId(long): List<Goal>
  + countByUserIdAndStatus(Long, GoalStatus): Integer
  + findByDeadline(LocalDate): List<Goal>
  + countByUserIdAndStatus(long, GoalStatus): Integer
  + countByUserIdAndStatusIn(long, List<GoalStatus>): Integer
}
class GoalRequest {
  - goalName: String
  - targetAmount: Double
  - deadline: LocalDate
  - savedAmount: Double
  - iconClass: String
  - iconColor: String
  + setGoalName(String): void
  + getGoalName(): String
  # canEqual(Object): boolean
  + getTargetAmount(): Double
  + setIconClass(String): void
  + getDeadline(): LocalDate
  + getSavedAmount(): Double
  + getIconClass(): String
  + toString(): String
  + getIconColor(): String
  + hashCode(): int
  + setTargetAmount(Double): void
  + setDeadline(LocalDate): void
  + setSavedAmount(Double): void
  + setIconColor(String): void
  + equals(Object): boolean
}
class GoalResponse {
  - iconColor: String
  - id: Long
  - iconClass: String
  - name: String
  - completed: boolean
  - targetAmount: double
  - savedAmount: double
  - userId: Long
  - deadline: LocalDate
  - status: GoalStatus
  + getId(): Long
  + getUserId(): Long
  + getName(): String
  + getTargetAmount(): double
  + getSavedAmount(): double
  + getDeadline(): LocalDate
  + getStatus(): GoalStatus
  + isCompleted(): boolean
  + getIconClass(): String
  + getIconColor(): String
}
class GoalService {
  - goalRepository: GoalRepository
  - userService: UserService
  + getGoalById(long, long): Goal
  - assertOwner(Goal, long): void
  + deleteGoal(long, long): void
  + getActiveGoalsCount(long): Integer
  + updateProgress(long, double, long): Goal
  + getGoalsByUserId(long): List<Goal>
  + addGoal(GoalRequest, long): Goal
  - calculateStatus(double, double): GoalStatus
  + editGoal(long, GoalRequest, long): Goal
}
enum GoalStatus << enumeration >> {
  + NEARLIMIT: 
  + ONTRACK: 
  + EXCEEDED: 
  + values(): GoalStatus[]
  + valueOf(String): GoalStatus
}
class JwtAuthenticationFilter {
  - tokenRepository: TokenRepository
  - jwtService: JwtService
  - userDetailsService: UserDetailsService
  - extractJwt(HttpServletRequest): String?
  # doFilterInternal(HttpServletRequest, HttpServletResponse, FilterChain): void
}
class JwtService {
  - secretKey: String
  - jwtExpiration: long
  - refreshExpiration: long
  + extractClaim(String, Function<Claims, T>): T
  + generateToken(UserDetails): String
  - buildToken(Map<String, Object>, UserDetails, long): String
  - isTokenExpired(String): boolean
  + generateToken(Map<String, Object>, UserDetails): String
  - getSignInKey(): SecretKey
  - extractAllClaims(String): Claims
  - extractExpiration(String): Date
  + extractUsername(String): String
  + generateRefreshToken(UserDetails): String
  + isTokenValid(String, UserDetails): boolean
}
class JwtTokenProvider {
  - jwtSecret: String
  - jwtExpirationMs: long
  + getUsernameFromToken(String): String
  - parseToken(String): Claims
  + generateToken(UserDetails): String
  + validateToken(String): boolean
}
class LogoutService {
  - tokenRepository: TokenRepository
  - extractJwtFromCookie(HttpServletRequest): String?
  + logout(HttpServletRequest, HttpServletResponse, Authentication): void
}
class MonthlyReportRequest {
  - endDate: LocalDate
  - startDate: LocalDate
  + getStartDate(): LocalDate
  + getEndDate(): LocalDate
  + setStartDate(LocalDate): void
  + setEndDate(LocalDate): void
  + equals(Object): boolean
  # canEqual(Object): boolean
  + hashCode(): int
  + toString(): String
}
class MonthlyReportResponse {
  - monthlyExpense: Map<Month, Double>
  - monthlyIncome: Map<Month, Double>
  - expenseByCategory: Map<String, Double>
  + getMonthlyExpense(): Map<Month, Double>
  + getMonthlyIncome(): Map<Month, Double>
  + getExpenseByCategory(): Map<String, Double>
  + setMonthlyExpense(Map<Month, Double>): void
  + setMonthlyIncome(Map<Month, Double>): void
  + setExpenseByCategory(Map<String, Double>): void
  + equals(Object): boolean
  # canEqual(Object): boolean
  + hashCode(): int
  + toString(): String
}
class Notification {
  - id: Long
  - createdAt: LocalDateTime
  - message: String
  - user: User
  - type: NotificationEventType
  - isRead: boolean
  + getType(): NotificationEventType
  + getId(): Long
  + getUser(): User
  + getMessage(): String
  + isRead(): boolean
  + getCreatedAt(): LocalDateTime
  + setType(NotificationEventType): void
  - $default$isRead(): boolean
  + setRead(boolean): void
  + setId(Long): void
  + setUser(User): void
  + setMessage(String): void
  + setCreatedAt(LocalDateTime): void
  + builder(): NotificationBuilder
}
class NotificationBuilder {
  - createdAt: LocalDateTime
  - message: String
  - isRead$value: boolean
  - isRead$set: boolean
  - user: User
  - type: NotificationEventType
  - id: Long
  + id(Long): NotificationBuilder
  + user(User): NotificationBuilder
  + message(String): NotificationBuilder
  + type(NotificationEventType): NotificationBuilder
  + isRead(boolean): NotificationBuilder
  + createdAt(LocalDateTime): NotificationBuilder
  + build(): Notification
  + toString(): String
}
class NotificationController {
  - notificationService: NotificationService
  - userService: UserService
  + getAllNotifications(UserDetails): ResponseEntity<List<NotificationResponse>>
  + deleteAllNotifications(UserDetails): ResponseEntity
  + markAsRead(Long): ResponseEntity
  - ResponseMapper(List<Notification>): List<NotificationResponse>
  + getRecentNotifications(int, UserDetails): ResponseEntity<List<NotificationResponse>>
  + getNotificationsByType(NotificationEventType, UserDetails): ResponseEntity<List<NotificationResponse>>
  + deleteNotification(Long): ResponseEntity
  + getUnreadNotifications(UserDetails): ResponseEntity<List<NotificationResponse>>
}
class NotificationEvent {
  - userId: Long
  + getUserId(): Long
  + getType(): NotificationEventType
}
enum NotificationEventType << enumeration >> {
  + GOAL_REMINDER: 
  + BUDGET_EXCEEDED: 
  + BUDGET_NEAR_LIMIT: 
  + valueOf(String): NotificationEventType
  + values(): NotificationEventType[]
}
interface NotificationRepository << interface >> {
  + findByType(NotificationEventType): List<Notification>
  + findByUserIdOrType(Long, NotificationEventType): List<Notification>
  + findByUserId(Long): List<Notification>
  + findByIdAndUserId(Long, Long): Optional<Notification>
  + findByUserIdAndIsReadFalse(Long): List<Notification>
}
class NotificationResponse {
  - createdAt: String
  - type: NotificationEventType
  - message: String
  - id: Long
  - read: boolean
  + setId(Long): void
  + getId(): Long
  + getType(): NotificationEventType
  + hashCode(): int
  + getMessage(): String
  + isRead(): boolean
  + getCreatedAt(): String
  # canEqual(Object): boolean
  + setType(NotificationEventType): void
  + setMessage(String): void
  + setRead(boolean): void
  + setCreatedAt(String): void
  + equals(Object): boolean
  + toString(): String
}
class NotificationService {
  - notificationRepository: NotificationRepository
  - userService: UserService
  + createNotification(NotificationEvent): void
  + markAsRead(Long): void
  - buildMessage(NotificationEvent): String
  + getUserNotifications(Long): List<Notification>
  + getReceivedNotifications(Long, int): List<Notification>
  + getUnreadNotifications(Long): List<Notification>
  + deleteAllNotifications(Long): void
  + deleteNotification(Long): void
  + getNotificationsByType(Long, NotificationEventType): List<Notification>
}
class PDFExporter {
  - getCategoryOrSource(Transaction): String
  - createCell(String, Font): PdfPCell
  + export(List<Transaction>, String): File
}
class PageController {
  + dashboardPage(): String
  + transactionsPage(): String
  + notificationPage(): String
  + profilePage(): String
  + reportsPage(): String
  + registerPage(): String
  + goalsPage(): String
  + budgetPage(): String
  + loginPage(): String
  + indexPage(): String
}
class PersonalBudgetApplication {
  + main(String[]): void
}
entity RegisterRequest << record >> {
  - email: String
  - password: String
  - name: String
  + name(): String
  + email(): String
  + password(): String
}
class ReportController {
  - userService: UserService
  - reportService: ReportService
  + getMonthlyReport(MonthlyReportRequest, UserDetails): ResponseEntity<MonthlyReportResponse>
  + downloadReport(ReportDownloadRequest, UserDetails): ResponseEntity<Resource>
  - trySetUserId(UserDetails, Consumer<Long>): boolean
  - getMediaType(String): MediaType
}
class ReportDownloadRequest {
  - startDate: LocalDate
  - endDate: LocalDate
  - format: ReportFormat
  + getEndDate(): LocalDate
  + getFormat(): ReportFormat
  + getStartDate(): LocalDate
  + setFormat(ReportFormat): void
  + setStartDate(LocalDate): void
  + setEndDate(LocalDate): void
  + equals(Object): boolean
  # canEqual(Object): boolean
  + hashCode(): int
  + toString(): String
}
interface ReportExporter << interface >> {
  + export(List<Transaction>, String): File
}
enum ReportFormat << enumeration >> {
  + CSV: 
  + EXCEL: 
  + PDF: 
  + valueOf(String): ReportFormat
  + values(): ReportFormat[]
}
class ReportService {
  - transactionService: TransactionService
  - exporterFactory: ExporterFactory
  + generateTransactionReport(Long, ReportDownloadRequest): File
  - getFileExtension(String): String
  + generateMonthlyReport(Long, MonthlyReportRequest): MonthlyReportResponse
}
enum Role << enumeration >> {
  + USER: 
  + ADMIN: 
  + valueOf(String): Role
  + values(): Role[]
}
class SecurityConfig {
  - jwtAuthFilter: JwtAuthenticationFilter
  - authenticationProvider: AuthenticationProvider
  - WHITE_LIST_URL: String[]
  - logoutHandler: LogoutHandler
  + securityFilterChain(HttpSecurity): SecurityFilterChain
}
class Token {
  + id: Integer
  + tokenType: TokenType
  - expired: boolean
  + user: User
  + token: String
  - revoked: boolean
  + getId(): Integer
  + getToken(): String
  + getTokenType(): TokenType
  + setUser(User): void
  + getUser(): User
  + setExpired(boolean): void
  + builder(): TokenBuilder
  + setId(Integer): void
  - $default$tokenType(): TokenType
  + setToken(String): void
  + setTokenType(TokenType): void
  + setRevoked(boolean): void
  + isExpired(): boolean
  + isRevoked(): boolean
}
class TokenBuilder {
  - token: String
  - user: User
  - tokenType$set: boolean
  - revoked: boolean
  - expired: boolean
  - tokenType$value: TokenType
  - id: Integer
  + id(Integer): TokenBuilder
  + token(String): TokenBuilder
  + tokenType(TokenType): TokenBuilder
  + revoked(boolean): TokenBuilder
  + expired(boolean): TokenBuilder
  + user(User): TokenBuilder
  + build(): Token
  + toString(): String
}
interface TokenRepository << interface >> {
  + findByToken(String): Optional<Token>
  + findAllValidTokenByUser(Long): List<Token>
}
enum TokenType << enumeration >> {
  + BEARER: 
  + values(): TokenType[]
  + valueOf(String): TokenType
}
class Transaction {
  - amount: double
  - source: String
  - category: Category
  - id: Long
  - user: User
  - date: LocalDate
  - type: TransactionType
  - description: String
  + getId(): Long
  + setId(Long): void
  + builder(): TransactionBuilder
  + setDate(LocalDate): void
  + getUser(): User
  + getCategory(): Category
  + setSource(String): void
  + getAmount(): double
  + getType(): TransactionType
  + setType(TransactionType): void
  + getDate(): LocalDate
  + setCategory(Category): void
  + setAmount(double): void
  + setDescription(String): void
  + getSource(): String
  + setUser(User): void
  + getDescription(): String
}
class TransactionBuilder {
  - amount: double
  - type: TransactionType
  - user: User
  - category: Category
  - description: String
  - date: LocalDate
  - id: Long
  - source: String
  + amount(double): TransactionBuilder
  + id(Long): TransactionBuilder
  + user(User): TransactionBuilder
  + category(Category): TransactionBuilder
  + type(TransactionType): TransactionBuilder
  + date(LocalDate): TransactionBuilder
  + source(String): TransactionBuilder
  + description(String): TransactionBuilder
  + build(): Transaction
  + toString(): String
}
class TransactionController {
  - transactionService: TransactionService
  - userService: UserService
  + getRecentTransactions(UserDetails): ResponseEntity<List<TransactionResponse>>
  + getAllTransactions(UserDetails): ResponseEntity<List<TransactionResponse>>
  + deleteTransaction(Long, UserDetails): ResponseEntity<Void>
  + updateTransaction(Long, CreateTransactionRequest, UserDetails): ResponseEntity<TransactionResponse>
  + getIncomeTransactions(UserDetails): ResponseEntity<List<TransactionResponse>>
  + getExpenseTransactions(UserDetails): ResponseEntity<List<TransactionResponse>>
  + addTransaction(CreateTransactionRequest, UserDetails): ResponseEntity<TransactionResponse>
  + filterTransactions(TransactionFilterRequest, UserDetails): ResponseEntity<List<TransactionResponse>>
}
class TransactionFilterRequest {
  - startDate: LocalDate
  - categoryId: Long
  - endDate: LocalDate
  + setCategoryId(Long): void
  + getStartDate(): LocalDate
  + getEndDate(): LocalDate
  + getCategoryId(): Long
  + setStartDate(LocalDate): void
  + setEndDate(LocalDate): void
  + equals(Object): boolean
  # canEqual(Object): boolean
  + hashCode(): int
  + toString(): String
}
class TransactionNotFoundException
interface TransactionRepository << interface >> {
  + getCategoryAmount(Long, TransactionType): List<Object[]>
  + findByUserIdAndType(Long, TransactionType): List<Transaction>
  + findByUserId(Long): List<Transaction>
  + findByUserIdAndDateBetween(Long, LocalDate, LocalDate): List<Transaction>
  + findTop5ByUserIdOrderByDateDescIdDesc(Long): List<Transaction>
  + sumByUserIdAndTypeAndDateBetween(Long, TransactionType, LocalDate, LocalDate): Double
  + findByUserIdAndDateBetweenAndCategoryId(Long, LocalDate, LocalDate, Long): List<Transaction>
  + countByUserId(Long): Integer
  + sumByUserIdAndType(Long, TransactionType): Double
  + getMonthlyTotal(Long, String, LocalDate, LocalDate): List<Object[]>
  + findByUserIdAndDateBetweenOrdered(Long, LocalDate, LocalDate): List<Transaction>
}
class TransactionResponse {
  - id: Long
  - source: String
  - description: String
  - amount: double
  - categoryId: Long
  - date: LocalDate
  - userId: Long
  - type: TransactionType
  + getId(): Long
  + getUserId(): Long
  + getCategoryId(): Long
  + getAmount(): double
  + getType(): TransactionType
  + getDate(): LocalDate
  + getSource(): String
  + getDescription(): String
}
class TransactionService {
  - budgetService: BudgetService
  - categoryService: CategoryService
  - transactionRepo: TransactionRepository
  - userService: UserService
  + getAllTransactions(Long): List<Transaction>
  + getUserService(): UserService
  + getExpenseTransactions(Long): List<Transaction>
  + getTransactionsByDateRange(Long, LocalDate, LocalDate): List<Transaction>
  + getRecentTransactions(Long): List<Transaction>
  + getMonthlyExpense(Long, LocalDate, LocalDate): Double
  + filterHistory(Long, TransactionFilterRequest): List<Transaction>
  + getMonthlyTotal(Long, MonthlyReportRequest, TransactionType): Map<Month, Double>
  + addTransaction(Long, CreateTransactionRequest): Transaction
  + getTotalIncome(Long): Double
  + updateTransaction(Long, Long, CreateTransactionRequest): Transaction
  + getTotalExpense(Long): Double
  + getIncomeTransactions(Long): List<Transaction>
  + getCategoryMap(Long, TransactionType): Map<String, Double>
  + getMonthlyIncome(Long, LocalDate, LocalDate): Double
  + getById(Long): Transaction
  + deleteTransaction(Long, Long): void
  + getNumberOfTransactions(Long): Integer
}
enum TransactionType << enumeration >> {
  + EXPENSE: 
  + INCOME: 
  + valueOf(String): TransactionType
  + values(): TransactionType[]
}
class UpdateNotificationSettings {
  - budgetAlerts: boolean
  - goalReminders: boolean
  + isBudgetAlerts(): boolean
  + isGoalReminders(): boolean
  + setBudgetAlerts(boolean): void
  + setGoalReminders(boolean): void
  + equals(Object): boolean
  # canEqual(Object): boolean
  + hashCode(): int
  + toString(): String
}
class User {
  - role: Role
  - budgetAlertenabled: boolean
  - name: String
  - id: Long
  - goalProgressAlertEnabled: boolean
  - email: String
  - password: String
  + getId(): Long
  + getName(): String
  + setGoalProgressAlertEnabled(boolean): void
  + getEmail(): String
  + getRole(): Role
  - $default$goalProgressAlertEnabled(): boolean
  - $default$budgetAlertenabled(): boolean
  + isBudgetAlertenabled(): boolean
  + isGoalProgressAlertEnabled(): boolean
  + setEmail(String): void
  + setPassword(String): void
  + setBudgetAlertenabled(boolean): void
  + builder(): UserBuilder
  + setRole(Role): void
  + setId(Long): void
  + setName(String): void
  + getUsername(): String
  + isAccountNonExpired(): boolean
  + getPassword(): String
  + isAccountNonLocked(): boolean
  + isCredentialsNonExpired(): boolean
  + getAuthorities(): Collection<GrantedAuthority>
  + isEnabled(): boolean
}
class UserBuilder {
  - email: String
  - budgetAlertenabled$value: boolean
  - role: Role
  - id: Long
  - budgetAlertenabled$set: boolean
  - name: String
  - password: String
  - goalProgressAlertEnabled$set: boolean
  - goalProgressAlertEnabled$value: boolean
  + id(Long): UserBuilder
  + name(String): UserBuilder
  + email(String): UserBuilder
  + password(String): UserBuilder
  + role(Role): UserBuilder
  + budgetAlertenabled(boolean): UserBuilder
  + goalProgressAlertEnabled(boolean): UserBuilder
  + build(): User
  + toString(): String
}
class UserProfileController {
  - userProfileService: UserProfileService
  - userService: UserService
  + getUserProfile(UserDetails): ResponseEntity<UserProfileResponse>
  + updateNotifications(UserDetails, UpdateNotificationSettings): ResponseEntity<Void>
  + editUserProfile(UserDetails, UserProfileRequest): ResponseEntity<UserProfileResponse>
}
class UserProfileRequest {
  - email: String
  - goalsCount: int
  - name: String
  - budgetsCount: int
  - role: Role
  - transactionsCount: int
  + getName(): String
  + setBudgetsCount(int): void
  + getEmail(): String
  + getRole(): Role
  + getTransactionsCount(): int
  + builder(): UserProfileRequestBuilder
  + setTransactionsCount(int): void
  + getGoalsCount(): int
  + getBudgetsCount(): int
  + setName(String): void
  + setGoalsCount(int): void
  + setRole(Role): void
  + hashCode(): int
  + toString(): String
  + setEmail(String): void
  + equals(Object): boolean
  # canEqual(Object): boolean
}
class UserProfileRequestBuilder {
  - name: String
  - goalsCount: int
  - role: Role
  - transactionsCount: int
  - budgetsCount: int
  - email: String
  + name(String): UserProfileRequestBuilder
  + email(String): UserProfileRequestBuilder
  + role(Role): UserProfileRequestBuilder
  + transactionsCount(int): UserProfileRequestBuilder
  + goalsCount(int): UserProfileRequestBuilder
  + budgetsCount(int): UserProfileRequestBuilder
  + build(): UserProfileRequest
  + toString(): String
}
class UserProfileResponse {
  - transactionsCount: int
  - name: String
  - budgetAlertEnabled: boolean
  - budgetsCount: int
  - goalsCount: int
  - email: String
  - role: Role
  - goalProgressAlertEnabled: boolean
  + getName(): String
  + setRole(Role): void
  + equals(Object): boolean
  + hashCode(): int
  + getEmail(): String
  + getRole(): Role
  + getTransactionsCount(): int
  + getGoalsCount(): int
  + getBudgetsCount(): int
  + isBudgetAlertEnabled(): boolean
  + setBudgetsCount(int): void
  + setGoalProgressAlertEnabled(boolean): void
  # canEqual(Object): boolean
  + setTransactionsCount(int): void
  + toString(): String
  + setBudgetAlertEnabled(boolean): void
  + isGoalProgressAlertEnabled(): boolean
  + setName(String): void
  + setEmail(String): void
  + builder(): UserProfileResponseBuilder
  + setGoalsCount(int): void
}
class UserProfileResponseBuilder {
  - email: String
  - role: Role
  - goalsCount: int
  - transactionsCount: int
  - budgetsCount: int
  - goalProgressAlertEnabled: boolean
  - budgetAlertEnabled: boolean
  - name: String
  + transactionsCount(int): UserProfileResponseBuilder
  + name(String): UserProfileResponseBuilder
  + email(String): UserProfileResponseBuilder
  + role(Role): UserProfileResponseBuilder
  + goalsCount(int): UserProfileResponseBuilder
  + budgetsCount(int): UserProfileResponseBuilder
  + budgetAlertEnabled(boolean): UserProfileResponseBuilder
  + goalProgressAlertEnabled(boolean): UserProfileResponseBuilder
  + build(): UserProfileResponse
  + toString(): String
}
class UserProfileService {
  - goalService: GoalService
  - budgetService: BudgetService
  - userService: UserService
  - transactionService: TransactionService
  - toDTO(User): UserProfileResponse
  + getUserProfile(UserDetails): UserProfileResponse
  + editUserProfile(UserDetails, UserProfileRequest): UserProfileResponse
}
interface UserRepository << interface >> {
  + findByEmail(String): Optional<User>
  + findIdByEmail(String): Optional<Long>
  + updateNotificationSettingsById(Long, boolean, boolean): void
}
class UserService {
  - userRepository: UserRepository
  + userExistsByEmail(String): boolean
  + getUserById(Long): User
  - getUserIdByEmail(String): Long
  + getAllUsers(): Iterable<User>
  + saveUser(User): User
  + updateNotificationSettings(UpdateNotificationSettings, long): void
  + getUser(UserDetails): User
  + deleteUserById(Long): void
  - getUserByEmail(String): User
  + getUserId(UserDetails): long
}

AdminController              "1" *-[#595959,plain]-> "transactionService\n1" TransactionService           
AdminController              "1" *-[#595959,plain]-> "userService\n1" UserService                  
ApplicationConfig            "1" *-[#595959,plain]-> "repository\n1" UserRepository               
AuthController               "1" *-[#595959,plain]-> "authenticationService\n1" AuthenticationService        
AuthenticationService        "1" *-[#595959,plain]-> "jwtService\n1" JwtService                   
AuthenticationService        "1" *-[#595959,plain]-> "tokenRepository\n1" TokenRepository              
AuthenticationService        "1" *-[#595959,plain]-> "userRepository\n1" UserRepository               
AuthenticationService        "1" *-[#595959,plain]-> "userService\n1" UserService                  
Budget                       "1" *-[#595959,plain]-> "status\n1" BudgetStatus                 
Budget                       "1" *-[#595959,plain]-> "category\n1" Category                     
Budget                       "1" *-[#595959,plain]-> "user\n1" User                         
BudgetBuilder                 +-[#820000,plain]-  Budget                       
BudgetController              -[#595959,dashed]->  BudgetResponse               : "«create»"
BudgetController             "1" *-[#595959,plain]-> "budgetService\n1" BudgetService                
BudgetController             "1" *-[#595959,plain]-> "userService\n1" UserService                  
BudgetExceededLimitEvent      -[#000082,plain]-^  NotificationEvent            
BudgetNearLimitEvent          -[#000082,plain]-^  NotificationEvent            
BudgetResponse               "1" *-[#595959,plain]-> "status\n1" BudgetStatus                 
BudgetService                 -[#595959,dashed]->  BudgetExceededLimitEvent     : "«create»"
BudgetService                 -[#595959,dashed]->  BudgetNearLimitEvent         : "«create»"
BudgetService                "1" *-[#595959,plain]-> "budgetRepository\n1" BudgetRepository             
BudgetService                "1" *-[#595959,plain]-> "categoryRepository\n1" CategoryRepository           
BudgetService                "1" *-[#595959,plain]-> "notificationService\n1" NotificationService          
BudgetService                "1" *-[#595959,plain]-> "userRepository\n1" UserRepository               
CSVExporter                   -[#008200,dashed]-^  ReportExporter               
Category                     "1" *-[#595959,plain]-> "type\n1" CategoryType                 
Category                     "1" *-[#595959,plain]-> "user\n1" User                         
CategoryBuilder               +-[#820000,plain]-  Category                     
CategoryController            -[#595959,dashed]->  CategoryResponse             : "«create»"
CategoryController           "1" *-[#595959,plain]-> "categoryService\n1" CategoryService              
CategoryController           "1" *-[#595959,plain]-> "userService\n1" UserService                  
CategoryResponse             "1" *-[#595959,plain]-> "type\n1" CategoryType                 
CategoryService              "1" *-[#595959,plain]-> "categoryRepository\n1" CategoryRepository           
CategoryService              "1" *-[#595959,plain]-> "userRepository\n1" UserRepository               
CreateCategoryRequest        "1" *-[#595959,plain]-> "type\n1" CategoryType                 
CreateTransactionRequest     "1" *-[#595959,plain]-> "type\n1" TransactionType              
DashboardController          "1" *-[#595959,plain]-> "budgetService\n1" BudgetService                
DashboardController           -[#595959,dashed]->  DashboardResponse            : "«create»"
DashboardController          "1" *-[#595959,plain]-> "goalService\n1" GoalService                  
DashboardController          "1" *-[#595959,plain]-> "transactionService\n1" TransactionService           
DashboardController          "1" *-[#595959,plain]-> "userService\n1" UserService                  
DashboardResponse            "1" *-[#595959,plain]-> "activeBudgetItems\n*" BudgetResponse               
DashboardResponse            "1" *-[#595959,plain]-> "recentTransactions\n*" TransactionResponse          
ExcelExporter                 -[#008200,dashed]-^  ReportExporter               
ExporterFactory              "1" *-[#595959,plain]-> "csvExporter\n1" CSVExporter                  
ExporterFactory              "1" *-[#595959,plain]-> "excelExporter\n1" ExcelExporter                
ExporterFactory              "1" *-[#595959,plain]-> "pdfExporter\n1" PDFExporter                  
Goal                         "1" *-[#595959,plain]-> "status\n1" GoalStatus                   
Goal                         "1" *-[#595959,plain]-> "user\n1" User                         
GoalBuilder                   +-[#820000,plain]-  Goal                         
GoalController                -[#595959,dashed]->  GoalResponse                 : "«create»"
GoalController               "1" *-[#595959,plain]-> "goalService\n1" GoalService                  
GoalController               "1" *-[#595959,plain]-> "userService\n1" UserService                  
GoalReminderEvent             -[#000082,plain]-^  NotificationEvent            
GoalReminderScheduler         -[#595959,dashed]->  GoalReminderEvent            : "«create»"
GoalReminderScheduler        "1" *-[#595959,plain]-> "goalRepository\n1" GoalRepository               
GoalReminderScheduler        "1" *-[#595959,plain]-> "notificationService\n1" NotificationService          
GoalResponse                 "1" *-[#595959,plain]-> "status\n1" GoalStatus                   
GoalService                   -[#595959,dashed]->  Goal                         : "«create»"
GoalService                  "1" *-[#595959,plain]-> "goalRepository\n1" GoalRepository               
GoalService                  "1" *-[#595959,plain]-> "userService\n1" UserService                  
JwtAuthenticationFilter      "1" *-[#595959,plain]-> "jwtService\n1" JwtService                   
JwtAuthenticationFilter      "1" *-[#595959,plain]-> "tokenRepository\n1" TokenRepository              
LogoutService                "1" *-[#595959,plain]-> "tokenRepository\n1" TokenRepository              
Notification                 "1" *-[#595959,plain]-> "type\n1" NotificationEventType        
Notification                 "1" *-[#595959,plain]-> "user\n1" User                         
NotificationBuilder           +-[#820000,plain]-  Notification                 
NotificationController        -[#595959,dashed]->  NotificationResponse         : "«create»"
NotificationController       "1" *-[#595959,plain]-> "notificationService\n1" NotificationService          
NotificationController       "1" *-[#595959,plain]-> "userService\n1" UserService                  
NotificationResponse         "1" *-[#595959,plain]-> "type\n1" NotificationEventType        
NotificationService          "1" *-[#595959,plain]-> "notificationRepository\n1" NotificationRepository       
NotificationService          "1" *-[#595959,plain]-> "userService\n1" UserService                  
PDFExporter                   -[#008200,dashed]-^  ReportExporter               
ReportController             "1" *-[#595959,plain]-> "reportService\n1" ReportService                
ReportController             "1" *-[#595959,plain]-> "userService\n1" UserService                  
ReportDownloadRequest        "1" *-[#595959,plain]-> "format\n1" ReportFormat                 
ReportService                "1" *-[#595959,plain]-> "exporterFactory\n1" ExporterFactory              
ReportService                 -[#595959,dashed]->  MonthlyReportResponse        : "«create»"
ReportService                "1" *-[#595959,plain]-> "transactionService\n1" TransactionService           
SecurityConfig               "1" *-[#595959,plain]-> "jwtAuthFilter\n1" JwtAuthenticationFilter      
Token                        "1" *-[#595959,plain]-> "tokenType\n1" TokenType                    
Token                        "1" *-[#595959,plain]-> "user\n1" User                         
TokenBuilder                  +-[#820000,plain]-  Token                        
Transaction                  "1" *-[#595959,plain]-> "category\n1" Category                     
Transaction                  "1" *-[#595959,plain]-> "type\n1" TransactionType              
Transaction                  "1" *-[#595959,plain]-> "user\n1" User                         
TransactionBuilder            +-[#820000,plain]-  Transaction                  
TransactionController         -[#595959,dashed]->  TransactionResponse          : "«create»"
TransactionController        "1" *-[#595959,plain]-> "transactionService\n1" TransactionService           
TransactionController        "1" *-[#595959,plain]-> "userService\n1" UserService                  
TransactionResponse          "1" *-[#595959,plain]-> "type\n1" TransactionType              
TransactionService           "1" *-[#595959,plain]-> "budgetService\n1" BudgetService                
TransactionService           "1" *-[#595959,plain]-> "categoryService\n1" CategoryService              
TransactionService            -[#595959,dashed]->  TransactionNotFoundException : "«create»"
TransactionService           "1" *-[#595959,plain]-> "transactionRepo\n1" TransactionRepository        
TransactionService           "1" *-[#595959,plain]-> "userService\n1" UserService                  
User                         "1" *-[#595959,plain]-> "role\n1" Role                         
UserBuilder                   +-[#820000,plain]-  User                         
UserProfileController        "1" *-[#595959,plain]-> "userProfileService\n1" UserProfileService           
UserProfileController        "1" *-[#595959,plain]-> "userService\n1" UserService                  
UserProfileRequest           "1" *-[#595959,plain]-> "role\n1" Role                         
UserProfileRequestBuilder     +-[#820000,plain]-  UserProfileRequest           
UserProfileResponse          "1" *-[#595959,plain]-> "role\n1" Role                         
UserProfileResponseBuilder    +-[#820000,plain]-  UserProfileResponse          
UserProfileService           "1" *-[#595959,plain]-> "budgetService\n1" BudgetService                
UserProfileService           "1" *-[#595959,plain]-> "goalService\n1" GoalService                  
UserProfileService           "1" *-[#595959,plain]-> "transactionService\n1" TransactionService           
UserProfileService           "1" *-[#595959,plain]-> "userService\n1" UserService                  
UserService                  "1" *-[#595959,plain]-> "userRepository\n1" UserRepository               
@enduml