@startuml infrastructure_module

skinparam linetype ortho

class GlobalExceptionHandler {
  + handleNotFound(TransactionNotFoundException): Map<String, Object>
}

class PersonalBudgetApplication {
  + main(String[]): void
}

@enduml